FROM golang:1.3

COPY . /usr/src/docker-gen
WORKDIR /usr/src/docker-gen

RUN go get -d -v
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -tags netgo -ldflags '-w -extldflags "-lpthread -static"' .
